version: '3.8'

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3000:3000"

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
        - api
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - "8080:8080"